name: CI # ci

on:
  push:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies with uv
        run: uv add

      - name: Run Black
        run: uv run black . --check

      - name: Run Ruff
        run: |
          uv run ruff check --select I
          uv run ruff check

      - name: Run Mypy
        run: uv run mypy .

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies with uv
        run: uv add

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest .
          uv run coverage report -m